### ISSUE TITLE
How do I --install a plugin so it always runs without being specified in a tsconfig?

### ISSUE THREAD

**Issue by Griffork** [nonara/ts-patch#109]
Hello!

I finally got the latest tspatch working (with typescript 5.1), I'm super excited to use the services patch to patch the runtime service so I can get compile-on-save support in my IDE back.

I want to create an npm module that I can use in a number of different project, that specifies a typescript compiler plugin. Ideally, as long as that npm module is installed, the plugin should run (regardless of what's listed in the tsconfig) every time tsc is called. 

My use-case is that I'd like to be able to just drop the npm module into a project and have the typescript compiler be modified.

How can I achieve this with tspatch?

P.S. Thanks nonara for the amazing work.

**Comment by samchon** [comment]
What you want is automatically configure `compilerOptions.plugins` field of `tsconfig.json` for convenience?

**Comment by nonara** [comment]
I have a plan for the new version of tsp to allow you to install / uninstall plugins via the commandline, but that's not implemented yet.

Even in that case, though, you'd need to specifically run the command for each project you want it to be in. Think of it like how `npm` works with packages. You need to add them to the project file.

One thing you could do is write a cli script in your module that you can run which would open tsconfig.json in `cwd` and add the config lines if they're not present.

Then you could install your module and simply run `my-cli -p tsconfig.json` for example. That would simplify it a bit.

**Comment by Griffork** [comment]
@samchon ideally I'd be able to add to it, yeah.

@nonara With the new version I would be able to run that command in my module's install script, right?

For now I'm going to investigate if I can monkey-patch `getProjectConfig` in `resources\module-patch.js` in ts-patch before running install or patch commands and see if it takes. Otherwise I'll probably fall back to what you're recommending.
