### ISSUE TITLE
tspc isn't found

### ISSUE THREAD

**Issue by charlesritchea** [nonara/ts-patch#110]
I have ts-patch ^2.0.0 as a devDependency and `    "prepare": "ts-patch install -s",
`  works, but I'd prefer to use tspc, but when I try to swap out tsc for tspc, tspc is not found. Is there some step I'm missing?

**Comment by charlesritchea** [comment]
```
With tools such as ts-node, webpack, ts-jest, etc: specify the compiler as ts-patch/compiler
```
In particular, I don't know what this means. I was calling ttsc with SpawnPlugin, is there something I need to set on ts-loader or ForkTs...?

**Comment by nonara** [comment]
Are you using ^2.0.0 or ^3.0.0?

V2 doesn't have tspc. You'd need to use v3.

As for specifying compiler, depending on which tool you're using there is an option called `compiler` that lets you specify a path to typescript. 

In `ttypescript`, you'd set it to `ttypescript`. 

In ts-patch, you can set it to `ts-patch/compiler`. You can see some examples for how on the ttypescript documentation.

However, if you're calling tspc via a plugin that should likely also work. You would only need to use one of those.

**Comment by charlesritchea** [comment]
@nonara v3 doesn't work for typescript < 5 is there documentation for v2 somewhere?

**Comment by nonara** [comment]
I see. There is no live compiler for v2, so you'd need to use the direct patch method. After that, you should be able to use it with any tool.

Best of luck!
