### ISSUE TITLE
Needs a typescript peer dependency?

### ISSUE THREAD

**Issue by ronakj** [nonara/ts-patch#127]
Particularly when trying to use the `TransformerExtras` type
![image](https://github.com/nonara/ts-patch/assets/2021979/fd8f3fb2-bf12-45cc-ad55-abaa5d124fea)

This code is straight up copied from README.md.

Note that we are using the new linked install strategy from NPM https://github.com/npm/rfcs/blob/e000b367d9e595bc694893c3d845df269f9b875f/accepted/0042-isolated-mode.md, if that makes a difference. (https://docs.npmjs.com/cli/v9/commands/npm-install#install-strategy)

**Comment by nonara** [comment]
Hello. Thanks for the report! It does rely on being able to resolve `import typescript` for the types, but I found that there was an issue with our built types that could have caused this. New version will be released shortly that fixes this!
