### ISSUE TITLE
What phase are transformers run ?

### ISSUE THREAD

**Issue by MarcWeber** [nonara/ts-patch#128]
I found this project cause it was linked from:
https://github.com/itsdouges/typescript-transformer-handbook

Which states TS has phases parser, binder, checker, transform, emitting

is it possible to run a transformer before the checker phase?

Eg turning qurey('SELECT * FROM USERS') into   query<{scheme here}>('select * FROM USERS') ?

If not would it even make sense to fork TypeScript and add that feature ?
if you add such directly after the parsing phase it should be somewhat maintainable ?

**Comment by tsengia** [comment]
`ts-patch` and other TypeScript transformers run during the `transform` stage. Most transform plugins using `ts-patch` perform transforms during the `before` step of the `transform` stage (ie. producing TypeScript before the TypeScript compiler transforms the TypeScript into JavaScript). 

For your example use case, it may be a better idea to express your table schemas as a TypeScript interface/class. Then you can add a transformer that transforms the methods of that class into more verbose (but faster) TypeScript much like [Typia](https://github.com/samchon/typia) does with parsing/serializing classes to/from JSON. Additionally, by expressing table schemas as TypeScript interfaces/classes, you would get IDE type hinting for free!

**Comment by nonara** [comment]
Transformation happens during emit in tsc.

There is experimental support to modify the language service to allow transformers, but I do not recommend doing that.
