### ISSUE TITLE
`program` transformer example from the documentation fails with `host.useCaseSensitiveFileNames is not a function`

### ISSUE THREAD

**Issue by canonic-epicure** [nonara/ts-patch#13]
Hi,

I'm trying to implement the `program` transformer and started with the example in the documentation: 
```ts
/** 
 * Add a file to Program
 */
import * as ts from 'typescript';
import * as path from 'path';
 
export const newFile = path.resolve(__dirname, 'added-file.ts');
 
export default function (program: ts.Program, host?: ts.CompilerHost) {
  return ts.createProgram(
    /* rootNames */ program.getRootFileNames().concat([ newFile ]),
    program.getCompilerOptions(),
    host,
    /* oldProgram */ program
  );
}
```

Unfortunately, it fails "out of the box" with `host.useCaseSensitiveFileNames is not a function` error message. 

It seems the transformer receives the empty `host` argument, but then later in the `parseConfigHostFromCompilerHostLike` there's an assumption it has the `useCaseSensitiveFileNames` property:

```
    /* @internal */
    function parseConfigHostFromCompilerHostLike(host, directoryStructureHost) {
        if (directoryStructureHost === void 0) { directoryStructureHost = host; }
        return {
            ........
            useCaseSensitiveFileNames: host.useCaseSensitiveFileNames(),
            .........
        };
    }
```

Am I missing something?

**Comment by canonic-epicure** [comment]
The TS version was 3.8.3, trying with 3.9.5

**Comment by canonic-epicure** [comment]
seems to be the same:
```
nickolay@frontier:~/workspace/typescript/typescript-transformer-test$ npx ts-patch install
[+] ts-patch installed!
nickolay@frontier:~/workspace/typescript/typescript-transformer-test$ npx tsc
host.useCaseSensitiveFileNames is not a function
nickolay@frontier:~/workspace/typescript/typescript-transformer-test$ npx tsc --version
Version 3.9.5
nickolay@frontier:~/workspace/typescript/typescript-transformer-test$ 
```

**Comment by canonic-epicure** [comment]
I've tried with:
```ts
/** 
 * Add a file to Program
 */
import * as ts from 'typescript'
import * as path from 'path'

export const newFile = path.resolve(__dirname, 'added-file.ts')

export default function (program : ts.Program, host? : ts.CompilerHost) {
    return ts.createProgram(
        program.getRootFileNames().concat([newFile]),
        program.getCompilerOptions(),
        ts.createCompilerHost(program.getCompilerOptions()),
        program
    )
}
```
which worked without errors, but I don't see the extra file `added-file.ts` emitted anywhere (both with and without "outDir" compiler option).

Am I missing something?

**Comment by nonara** [comment]
I can't re-produce the issue. That seems rather strange, also, as passing undefined for host should be fine. 

The one area where you may run into problems is if the `typescript` instance you're importing differs from the one which called the transformer.

You can mitigate that by making sure you use the one provided.

ie:

```ts
/** 
 * Add a file to Program
 */
import * as ts from 'typescript';
import * as path from 'path';
 
export const newFile = path.resolve(__dirname, 'src/added-file.ts');
 
export default function (program: ts.Program, host?: ts.CompilerHost, options: any, { ts: tsInstance }: { ts: typeof ts }) {
  return tsInstance.createProgram(
    /* rootNames */ program.getRootFileNames().concat([ newFile ]),
    program.getCompilerOptions(),
    host,
    /* oldProgram */ program
  );
}
```

**Comment by canonic-epicure** [comment]
This is what I've started from. Double checking the TS versions.

**Comment by canonic-epicure** [comment]
The code you posted fails with `Cannot destructure property 'ts' of 'undefined' as it is undefined`

The original code still fails with the same error:

About the

> The one area where you may run into problems is if the typescript instance you're importing differs from the one which called the transformer.

Does that mean that versions of TS need to match, or it needs to be exactly the same TS instance, currently its a different instance, yes.

**Comment by canonic-epicure** [comment]
Perhaps you meant this signature:

```ts
export default function (program : ts.Program, host? : ts.CompilerHost, options? : { ts : typeof ts }) {
...
}
```

This works correctly (still have to replace `host` with `ts.createCompilerHost(program.getCompilerOptions())`). But no `added-file.js` anywhere in the output again. Perhaps its because it is located in the transfomer's source tree?

**Comment by canonic-epicure** [comment]
So I was missing how the "program" transformers are specified.

Docs says: 
```
type | Plugin entry point format (see: Type Signatures)
```

And in the "Type Signatures" the first line says:
```
program (default)
```
So I've happily configured my transformer as:
```
        "plugins": [
            { "transform": "../typescript-transformer-lazy-property/src/Transformer.ts", "type" : "program" }
        ],
```
Whereas, after examining docs more thoroughly, it needs to be:
```
        "plugins": [
            { "transform": "../typescript-transformer-lazy-property/src/Transformer.ts", transformProgram : true }
        ],
```

Perhaps its worth updating the docs (removing the "program" from the "type" list).

**Comment by canonic-epicure** [comment]
Oh, actually, there is an example of configuration similar to mine:
```
{
    "compilerOptions": {
        "plugins": [
            { "transform": "./transformers/my-transformer.ts", "type": "program" },
        ]
    }
}
```
But it is clearly incorrect.

**Comment by canonic-epicure** [comment]
Oh, yes, now the `host` config is filled, of course.

**Comment by nonara** [comment]
Glad you got it working! Thanks for the update.

**Comment by canonic-epicure** [comment]
@nonara Point is - docs are incorrect.

**Comment by nonara** [comment]
The documentation is not incorrect. The `type` property applies to _source transformers_, which are a native part of the typescript compiler. They simply aren't integrated into TSC. `ts-patch` and `ttypescript` work around this by allowing them to be added to the build process via `tsconfig.json`.

The labels for `type` indicate the signature type for a source transformer. They were created by `ttypescript` and cannot be changed without breaking compatibility, which I do not want to do.

**Program transformers** are a novel concept, newly introduced in `ts-patch`. The documentation states:

----
"... ts-patch now supports this via a **transformProgram** plugin. The transform action takes place during ts.createProgram.

There is only one possible signature for a Program transformer.

```(program: ts.Program, host: ts.CompilerHost | undefined, options: PluginConfig, extras: ProgramTransformerExtras) => ts.Program```

...

Notes
**A Program transformer is not a Node Transformer.** This means the following options will not apply when **transformProgram: true is specified:**

**type**
before
after"

----

With that said, I will look into adding a note or two to the `type` section and revising some wording to make it more clear.

**Comment by nonara** [comment]
I've updated the docs. Hopefully they are more clear now!

**Comment by canonic-epicure** [comment]
Thank you! Will definitely save time for future new users!
