### ISSUE TITLE
Support for tsc 5.3

### ISSUE THREAD

**Issue by Griffork** [nonara/ts-patch#133]
Typescript 5.3 reports a Consolidation Between tsserverlibrary.js and typescript.js

Which I imagine means some of the hooks need to be changed and/or how the pathc is installed needs to change.

When will this be supported/is it already supported?

**Comment by samchon** [comment]
Not working on ts 5.3 beta

**Comment by nonara** [comment]
@Griffork I assume consolidation won't change anything.

@samchon I haven't tried yet. But we'll make sure it works before release. Is it failing to patch all binaries or do you get a specific error message?

**Comment by samchon** [comment]
I will make a reproducible repo after an hour. Thanks for quick response

**Comment by nonara** [comment]
@samchon Thanks! No need to make a repro, though. I'll use the main repo + tests.

But if you have any diagnostic info, feel free to share here!

**Comment by samchon** [comment]
@Griffork @nonara I want to correct my report something wrong. 

At first, about the TypeScript v5.3 beta update, no issues with normal `ts-patch` use cases.

The problem appears only when targeting a transformer by original TypeScript source file `*.ts` like below:

- No problem in normal use case: https://github.com/samchon/ts-patch-typescript-v5.3-test
- Failed to transform when targetting `*.ts` file: https://github.com/samchon/typia/tree/typescript%405.3.0-beta

https://github.com/samchon/typia/blob/97b975f12a494bb1918f2ce30ab8e675b148a06d/test/tsconfig.json#L106-L113
