### ISSUE TITLE
Enable `defaultJSDocParsingMode` of TypeScript v5.3

### ISSUE THREAD

**Issue by samchon** [nonara/ts-patch#134]
## Outline
https://github.com/microsoft/TypeScript/pull/55739

After TypeScript v5.3 being released, it will no more parse `JSDocComments` as default. 

To turn it on, `ts.Program` instance must be created with `ts.CompilerHost.jsDocParsingMode` configuration like below. By the way, transformer libraries can't create the `ts.Program` instance by themselves, so if there're some transformer libraries utilizing the `JSDocComment` feature, they would be disabled after the TypeScript v5.3 release.

> Especially, my library [typia](https://typia.io/docs/json/schema/#specialization) be damaged.

```typescript
const options: ts.CompilerOptions;
const host: ts.CompilerHost = ts.createCompilerHost(options);
const program: ts.Program = ts.createProgram(["source files..."], options, host);
```

To support those `JSDocComment` utilizing transformers, `ts-patch` needs to hack the `defaultJSDocParsingMode` variable of below.

> https://github.com/microsoft/TypeScript/pull/55739#issuecomment-1728566241 -> `ts-patch` author @nonara be tagged

## Suggestion
I think there can be two options.

  - Just hack the `defaultJSDocParsingMode` value globally
  - Special CLI argument `ts-patch install --jsDoc`

The 1st way is to changing the `defaultJSDocParsingMode` variable of `tsc` to be `0` as default. 

Comparing with other fast compilers like `swc` and `esbuild`, standard TypeScript compiler is hundreds of times slower. Therefore, as transformer library users are already enduring such slower compilation speed, I think they may not consider about the performance enhancement by skipping `JsDocComment` parsing.

The 2nd way is to providing special CLI argument `ts-patch install --jsDoc`.

Although saving compilation time by ignoring `JsDocComment` does not mean for transformer library users, it is the new formal spec of the standard TypeScript compiler. Therefore, rather than changing the `defaultJSDocParsingMode` variables globally, it may be more correct to give the user a choice.

**Comment by nonara** [comment]
Thanks for the research, @samchon !

I think the best route would be to add a plugin config option which allowed the user to specify jsdoc parsing mode.

If we have default be off, then plugin packages that rely on it will need to update their docs.

Conversely, if default is on, `tspc` will be lose speed optimizations by default.

I generally hate to put the burden of keeping up on the plugin maintainers, especially as some aren't maintained anymore. At the same time, it's difficult to justify slowing everyone else down by default.

I'm open to input on this from you or anyone else.

Right now, I think I'm inclined toward leaving the default to off and requiring an extra config option in the plugins entry.

**Comment by samchon** [comment]
Yes, the 2nd way would be suitable for the goal of TypeScript v5.3 update.

By the way, may I add a new idea about the 2nd way? 

I'd thought about the `ts-patch install --jsDoc` option again, and it may be burden and annoying job for transformer library users. I think the configuration must be guided from transform library authors when setting them up, instead of the using global CLI argument, so that it would better to changing the `tsconfig.json` file like below.

```json
{
  "compilerOptions": {
    "plugins": [
      { 
        "transform": "typia/lib/transform",
        "parseJSDoc": true // not a matter whatever the variable name be
      }
    ]
}
```

**Comment by nonara** [comment]
Thanks for the research, @samchon !

I think the best route would be to add a plugin config option which allowed the user to specify jsdoc parsing mode.

If we have default be off, then plugin packages that rely on it will need to update their docs.

Conversely, if default is on, `tspc` will be lose speed optimizations by default.

I generally hate to put the burden of keeping up on the plugin maintainers, especially as some aren't maintained anymore. At the same time, it's difficult to justify slowing everyone else down by default.

I'm open to input on this from you or anyone else.

Right now, I think I'm inclined toward leaving the default to off and requiring an extra config option in the plugins entry.

**Comment by nonara** [comment]
Yes, that is what I was referring to here

> I think the best route would be to add a plugin config option which allows the user to specify jsdoc parsing mode.

**Comment by samchon** [comment]
Ts v5.3 be released, and time to determine the spec.

**Comment by samchon** [comment]
Considering this spec, I think the cashing feature no more can maintainable, and just check the `tsc.js` and `tsclibrary.js` files manually whenever running the `ts-patch install` command. The good new is that, as `ts-patch install` command only takes a moment, and it would not be executed such a lot repeated, there would not be significant problem.

How do you think about @nonara ?

**Comment by nonara** [comment]
Ok. Doing this properly required a little bit of thought. I didn't like the option of universally overriding the default mode for tsc and losing the perf gains. The idea of forcing all end users to add something to their plugin entry config for libraries like `typia` was even worse.

I decided to take another step toward what we'll be doing in tsp-next and allow for basic configuration to be set within the actual plugin library itself.

Here's the working PR if you'd like to check it out: https://github.com/nonara/ts-patch/pull/138

I haven't it tested yet or added any tests. I'll try with typia tomorrow and ensure it works.

## How It Works

What you'd be able to do here is specify configuration inside of typia's package.json file.

Something like this:

`package.json`
```
{
  // ...
  "tsp": {
    "tscOptions" : {
      "parseAllJsDoc": true
    }
  }
}
```

This will allow plugin authors to specify that they need full JSDoc parsing. The way it works now, it will preload the config for all plugins, and if any require that option, it will ensure that the host is updated to use the `ParseAll` mode before creating the program.

Feel free to let me know if you have any comments on that approach.

**Comment by nonara** [comment]
I think you're misunderstanding what we're doing.

If this was a setting that we wanted the user to be able to provide, we'd simply add it as another option for the plugin entry in tsconfig.

However, if we did that, all of your users would need to change their tsconfig to make it work.

What I've done is made it so that _you_ can add config on your library's side, so that users don't have to change anything. In that case, you simply add the clause to your package.json. That will inform tsp that the plugin within your package requires full jsdoc during tsc.

It doesn't make sense to use tsconfig there, as most libraries don't ship their tsconfig file, but all have a package file.

The way we're doing it is a common convention for this sort of thing, and it provides a place within the package file to define tsp specific detail.

Also – we definitely wouldn't add anything to `compilerOptions` or any other official tsconfig location. That's something I wish ttypescript had never done. In the future, we'll be moving to a special tsp section in tsconfig.

**Comment by nonara** [comment]
Added to `v3.1.0`
