### ISSUE TITLE
run transformer on .d.ts file

### ISSUE THREAD

**Issue by shivamp2404** [nonara/ts-patch#137]
I want to run the transformer on the .d.ts files directly, but this doesn't seems to work.
Basically my use case is to extract some type from the .d.ts files from the node_modules and store them in a different files.
I've tried adding node_modules in include[] of tscong.json, but the transformer doesn't seems to be running on the .d.ts files.

**Comment by nonara** [comment]
@shivamp2404 ts-patch hooks into the emit process. Declarations files are not treated as input files for compilation, so they do not get transformed.

You can use the Compiler API to manually transform declarations files, however.

Here's a minimal example from [ts-expose-internals](https://github.com/nonara/ts-expose-internals/blob/master/src/ts-declarations.ts)

```
  // Load file content into dtsContent

  /* Parse the source file */
  const sourceFile = ts.createSourceFile('typescript.d.ts', dtsContent, ts.ScriptTarget.ES2018, true);

  /* Transform */
  const result = ts.transform(sourceFile, [ transformDts ]);

  /* Print the transformed output */
  const printer = ts.createPrinter();
  const output = printer.printNode(ts.EmitHint.Unspecified, result.transformed[0], sourceFile);

  // Save output to destination file
```
