### ISSUE TITLE
Not working on TypeScript v5.5 update

### ISSUE THREAD

**Issue by samchon** [nonara/ts-patch#152]
Here is the reproducible repo, and you can see that `ts-patch` is not working on the `typescript@5.5`.

  - Repository: https://github.com/samchon/ts-patch-typescript-5.5
  - Actions Result: https://github.com/samchon/ts-patch-typescript-5.5/actions/runs/8857098649/job/24324161172
  - Try on browser (StackBlitz): https://stackblitz.com/~/github.com/samchon/ts-patch-typescript-5.5

**Comment by nonara** [comment]
Hey @samchon! Thanks for the report. Will check it out

**Comment by nonara** [comment]
They made some pretty interesting changes. I had to add a new slicer and update some other logic, but I believe I have it working.

There is just one test failing now. From what I can tell, it looks like they don't always actually have a `ts` instance. They seem to be doing some dynamic logic to prepare for handling ESM, or maybe they already are. I saw some discussion about it on Twitter, but didn't follow too closely.

To accommodate that, I added this to our patch source, and I call it whenever we need to find what used to be the `ts` namespace.

![image](https://github.com/nonara/ts-patch/assets/1427565/3c974434-82fc-4dca-bd68-1b18089b535a)

It's late here, so I'm going to call it a night, but if you want to take a look here is the PR:

- #154 

I'm hoping the issue will be fairly easy to figure out. It may be as simple as just needing to expand the `getTsInstance()` function to accommodate whatever it should be in the case of its "esm mode".

## Detail & Notes

Seems to happen here:

```
   Command failed: node run-transform.js ts
    file:///C:/Users/ron/AppData/Local/Temp/tsp/esm/f7dfb328032bdd6492d9f6eebfbacbfd.mjs:2
    ReferenceError: exports is not defined
```

_Note to self:
I'm not sure if maybe we no longer need to use the `esm` package and wrap require in this case — if they finished full esm support, we can probably add in some logic where we only use the `esm` library if we need to. If memory serves, we may skip waiting for require throw if we know the file extension is esm ahead of time._

**Comment by nonara** [comment]
I also found this nasty issue, which seems to affect older ts-patch on Node 21+

- #153

I think this is an actual bug in Node, as the error does not make sense, especially given the diagnostic data.

**Comment by nonara** [comment]
Updated and working in [v3.2.0](https://github.com/nonara/ts-patch/releases/tag/v3.2.0)

@samchon Let me know if you have any issues!

**Comment by GulgDev** [comment]
I'm still getting this issue on Node v22.5.1 and TypeScript 5.5.4 with ts-patch 3.2.1

**Comment by GulgDev** [comment]
```
D:\sandbox\TypiaTest\node_modules\typescript\lib\tsc.js:135
                        const res = getEsmLibrary()(newModule)(targetFilePath);
                                                              ^
TypeError: Function.prototype.apply was called on undefined, which is a undefined and not a function
    at Module.wrappedRequire (D:\sandbox\TypiaTest\node_modules\typescript\lib\tsc.js:135:63)
    at require (node:internal/modules/helpers:123:16)
    at loadEntryFile (D:\sandbox\TypiaTest\node_modules\typescript\lib\tsc.js:401:31)
    at TspPlugin.createFactory (D:\sandbox\TypiaTest\node_modules\typescript\lib\tsc.js:379:44)
    at PluginCreator.createSourceTransformers (D:\sandbox\TypiaTest\node_modules\typescript\lib\tsc.js:270:56)
```

**Comment by GulgDev** [comment]
Fixed by removing `"type": "module"` from `package.json`
