### ISSUE TITLE
how to debug transformers in vs code 

### ISSUE THREAD

**Issue by chandu0101** [nonara/ts-patch#158]
Currently i am using `console.log()` for debugging in transformers source code, 
is it possible to use vscode to debug `tsc -w` command.

**Comment by samchon** [comment]
https://github.com/samchon/nestia-start/blob/master/.vscode/launch.json

How about referencing this one? 

I'm debugging `ts-patch` transformed project through compiled JS files.

**Comment by chandu0101** [comment]
thanks for reply ,
debugging link you provided works fine on my project files , but i want debug transformer source code.

https://github.com/chandu0101/ts_codegen

debug points in  `./build/index.js`  working fine , but break points in  `./buld/transformer.js` not hitting

**Comment by nonara** [comment]
@chandu0101 I use the debugger for transformers often.

Try using tsc without watch mode. It's likely that is your issue. If you're using typescript-based transformers you should be able to set breakpoints in the `.ts` files, otherwise you can do it in the `.js` files
