### ISSUE TITLE
Not working on TypeScript 5.5.2

### ISSUE THREAD

**Issue by DiFuks** [nonara/ts-patch#159]
Branch for reproduction: https://github.com/DiFuks/ts-overrides-plugin/tree/ts-5.5.2

GHA: https://github.com/DiFuks/ts-overrides-plugin/actions/runs/9603473575/job/26486752499

However, with version 5.5.1-rc, this problem does not occur, and the plugin works perfectly. GHA: https://github.com/DiFuks/ts-overrides-plugin/actions/runs/9603497686/job/26486838709

Difference between branches: https://github.com/DiFuks/ts-overrides-plugin/compare/ts-5.5.2...ts-5.5.1-rc

**Comment by osyrisrblx** [comment]
Looks like the regex against `lib/typescript.js` is failing.

## [`5.5.1-rc`](https://www.unpkg.com/typescript@5.5.1-rc/lib/typescript.js)
```js
// ...
});
})(typeof module !== "undefined" && module.exports ? module : { exports: ts });
if (typeof module !== "undefined" && module.exports) { ts = module.exports; }
//# sourceMappingURL=typescript.js.map
```

## [`5.5.2`](https://www.unpkg.com/typescript@5.5.2/lib/typescript.js)
```js
// ...
});
})({ get exports() { return ts; }, set exports(v) { ts = v; if (typeof module !== "undefined" && module.exports) { module.exports = v; } } })
//# sourceMappingURL=typescript.js.map
```
