### ISSUE TITLE
Use with typescript-plugin-css-modules

### ISSUE THREAD

**Issue by bensaufley** [nonara/ts-patch#167]
I'm sorry if I'm just missing something obvious but I've dug through the source code of both https://github.com/mrmckeb/typescript-plugin-css-modules and this project and I can't quite figure out how to make them work together. The plugin works in my VSCode Language Service with this config:

```json
    {
        "name": "typescript-plugin-css-modules",
        "options": {
          "classnameTransform": "camelCase",
          "goToDefinition": true
        }
    }
```

But no combination of options with `"transform": "typescript-plugin-css-modules"` seems to work (tried `"type": "ls"` since it works with a LS, `"type": "checker"` since that's what it's used for, obviously tried the default `"program"`, and `"config"` and `"compilerOptions"` just for good measure). The plugin returns an object with `create` and `getExternalFiles`; ts-patch is saying `expected a function or an object with a 'before' property`, which it obviously doesn't have. With `"transformProgram": true` it seems like the plugin is just not used at all.

My _expectation_ is that I need to do something with a LanguageService somewhere to get this working but the `ts-patch` docs don't offer much in the way of how to do that:

> you'll need to create a LanguageService plugin to accompany your source transformer

Am I fundamentally misunderstanding something here? Probably. Is there a way to make this plugin play nice with `ts-patch`?

**Comment by nonara** [comment]
From what I can tell, that plugin is a language service plugin only, which means you don't need ts-patch.

TypeScript natively supports language service plugins. Those can only extend functionality in your IDE. They cannot affect output compiled files. 

ts-patch extends the TypeScript compiler so you can also add transformers to affect output files.

The documentation page for the plugin you mentioned shows an example of how to set it up using `compilerOptions`. I'd suggest using that example, and if you have any problems, file an issue on that repo.

Best of luck!

**Comment by bensaufley** [comment]
@nonara thanks for the quick response! I'm sorry I should've been more clear in what I was looking for: I'm looking for parity in typechecking between my IDE and the command line. So e.g. in our CI we run `tsc --noEmit` to make sure no violations are introduced in a PR. With this plugin, I can add `noUncheckedIndexAccess` and still use CSS modules _in my IDE_, but CSS modules still present violations using `tsc --noEmit`. What I'd like to be able to do is hook this plugin into `ts-patch` so that I can run `tpsc --noEmit` and again have parity between what my IDE shows and what the CLI shows for typechecking. As it is now, I have all sorts of violations that aren't actually violations because they properly reference CSS modules.

**Comment by nonara** [comment]
Understood. There are essentially two phases. The language service is in IDE only and the compiler (tsc) is separate.

ts-patch does provide functionality to add diagnostics during tsc, but the plugin would need to support it.

Sounds like you'd need to do a PR to the plugin. 

Others have done similar things. If you want it to work using noEmit, what you'd likely want to do is use a Program Transformer pattern and supplement the added diagnostics into the resulting arrays by wrapping the diagnostics functions on ts.

There is an open issue where someone did exactly that, which can serve as a reference.
