### ISSUE TITLE
Enhancement: Detect/supply tsconfig.json for transformer (+support path mapping)

### ISSUE THREAD

**Issue by LukasMachetanz** [nonara/ts-patch#17]
Hi everyone!

I am wondering if the `paths` compiler option in `tsconfig` should work in combination with `ts-patch`? Unfortunately I always get an error:

> ERROR in Error: Cannot find module '@ttransformer/my-lib'

Paths defined like this in `tsconfig.json`: `  "paths": { "@ttransformer/my-lib": ["libs/my-lib/src/index.ts"] }`.

I am currently developing a library in an `nrwl/nx` workspace. I am including this library in an angular application (tsconfig.spec.json) like described in the documentation: ` "plugins": [{ "transform": "./libs/core/src/index.ts" }]`. Unfortunately I receive the mentioned error. 

I am wondering if this is maybe because of `ts-patch` and `ttypescript`. Any help appreciated.

Thanks. Greets Lukas

**Comment by nonara** [comment]
Hi Lukas. Can you paste the package.json and tsconfig file(s) for your package, please?

**Comment by LukasMachetanz** [comment]
**package.json** from the nx-workspace:

```
{
  "name": "ttransformer",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "nx": "nx",
    "start": "nx serve",
    "build": "nx build",
    "test": "nx test",
    "lint": "nx workspace-lint && nx lint",
    "e2e": "nx e2e",
    "affected:apps": "nx affected:apps",
    "affected:libs": "nx affected:libs",
    "affected:build": "nx affected:build",
    "affected:e2e": "nx affected:e2e",
    "affected:test": "nx affected:test",
    "affected:lint": "nx affected:lint",
    "affected:dep-graph": "nx affected:dep-graph",
    "affected": "nx affected",
    "format": "nx format:write",
    "format:write": "nx format:write",
    "format:check": "nx format:check",
    "update": "nx migrate latest",
    "workspace-schematic": "nx workspace-schematic",
    "dep-graph": "nx dep-graph",
    "help": "nx help",
    "playground": "sh ./libs/playground/playground.sh",
    "postinstall": "ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points",
    "install-ts-patch": "ts-patch install"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^9.1.0",
    "@angular/common": "^9.1.0",
    "@angular/compiler": "^9.1.0",
    "@angular/core": "^9.1.0",
    "@angular/forms": "^9.1.0",
    "@angular/platform-browser": "^9.1.0",
    "@angular/platform-browser-dynamic": "^9.1.0",
    "@angular/router": "^9.1.0",
    "rxjs": "~6.5.4",
    "zone.js": "^0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.901.0",
    "@angular/compiler-cli": "^9.1.0",
    "@angular/language-service": "^9.1.0",
    "@nrwl/cypress": "9.5.1",
    "@nrwl/eslint-plugin-nx": "9.5.1",
    "@nrwl/jest": "^9.5.1",
    "@nrwl/node": "^9.5.1",
    "@nrwl/workspace": "9.5.1",
    "@phenomnomnominal/tsquery": "^4.1.0",
    "@types/jasmine": "~2.8.8",
    "@types/jest": "25.1.4",
    "@types/node": "~8.9.4",
    "@typescript-eslint/eslint-plugin": "2.19.2",
    "@typescript-eslint/parser": "2.19.2",
    "codelyzer": "~5.0.1",
    "cypress": "^4.1.0",
    "dotenv": "6.2.0",
    "eslint": "6.8.0",
    "eslint-config-prettier": "6.0.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "jest": "25.2.3",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "prettier": "2.0.4",
    "ts-jest": "25.2.1",
    "ts-node": "^7.0.1",
    "ts-patch": "^1.2.5",
    "tslint": "~6.0.0",
    "ttypescript": "^1.5.10",
    "typescript": "~3.8.3"
  }
}
```

**tsconfig.spec.json**  from the Angular application:

```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "types": ["jasmine", "node"],
    "plugins": [{ "transform": "./libs/core/src/index.ts" }]
  },
  "files": ["src/test.ts", "src/polyfills.ts"],
  "include": ["**/*.spec.ts", "**/*.d.ts"]
}
```

**tsconfig.json**  from the Angular application:

```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "types": ["jasmine"]
  }
}
```

**tsconfig.json**  from the nx-workspace:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "typeRoots": ["node_modules/@types"],
    "lib": ["es2017", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "paths": {
      "@ttransformer/core": ["libs/core/src/index.ts"],
      "@ttransformer/shared": ["libs/shared/src/index.ts"],
    }
  },
  "exclude": ["node_modules", "tmp"]
}
```

`@ttransformer/core` is a `buildable` `@nrwl/node` library. This library internally uses `@ttransformer/shared` (also a buildable @nrwl/node library).

The Angular application uses the transformer program defined in `@ttransformer/core`. The error appears because the import statement from `@ttransformer/shared` used in `@ttransformer/core`  can not be resolved.

Error:
> ERROR in Error: Cannot find module '@ttransformer/shared'

Using something directly in the specs of the Angular application (importing with the path alias) works though. That's why my first guess was a problem with `ts-patch` or `ttypescript`?

**Comment by nonara** [comment]
At the moment, if a transformer is a `.ts` file, it uses ts-node to load it with a basic set of `compilerOptions`. This was the standard behaviour of `ttypescript`, on which it was based.

I believe the original intent for `ttypescript` was to allow you to load `.js` transformers, or optionally a _slim) `.ts` transformer. It wasn't really built to work load a whole typescript project as a transformer. Which makes sense, as the additional overhead in compilation time isn't desirable. Best practice is to compile the transformer when you make a change to it, and use the compiled `.js` file in your plugin entry. This cuts down the extra drag during compilation time.

With that said, I've run into situations myself where it would be beneficial to make use of a `tsconfig` file for the transformer. Determining a location for a ts-config file is surprisingly something that isn't in the typescript compiler API. That has been something of a pain point for those of us working with it. But it wouldn't be difficult to write one.

Anyway, I think it'd be a worthwhile change to make it walk up the directories to try to find and load a valid `tsconfig.json` file and/or to add a `tsconfig` option for plugin entries to manually specify one. 

For paths, we'd also have to make it automatically register with `tsconfig-paths` if `paths` were specified in the tsconfig.

I'm going to add an enhancement tag on this.

## In the meantime

I would suggest the following:

1. You can compile your transformer (using a plugin that updates the mapped paths with the proper ones in the js output)
2. Set `transform` to the `.js` path of your compiled transformer

**Comment by LukasMachetanz** [comment]
Okay. Thank's for the explanation and the support. 

Regarding your suggestion **1)**: Do you think of a specific plugin? So any suggestions?

**Comment by nonara** [comment]
@LukasMachetanz np! I use [typescript-transform-paths](https://www.npmjs.com/package/typescript-transform-paths)

If you need to make sure it transforms declaration files paths also, use two entries:

```jsonc
{
  "compilerOptions": {
    "plugins": [
      { "transform": "typescript-transform-paths" },
      { "transform": "typescript-transform-paths", "afterDeclarations": true },
    ]
  }
}
```

**Comment by nonara** [comment]
As of 1.3.0, You can now supply a 'tsConfig' property in your plugin config to specify a path to the tsconfig file for your transformers.

It will support path mapping if you have `tsconfig-paths` installed as development dependency.

**Comment by LukasMachetanz** [comment]
Hi. Thank you for tackling the issue. But unfortunately I could not get it to run in my `nx-workspace`.

Can you maybe have a look at the following line if the configuration is done as intended:
https://github.com/LukasMachetanz/ttransformer/blob/9c8c903bd97f91dcf7318dc81891c13e0c6c795e/apps/angular-karma-demo/tsconfig.spec.json#L7

I would like to use the transformer defined here:
https://github.com/LukasMachetanz/ttransformer/blob/9c8c903bd97f91dcf7318dc81891c13e0c6c795e/libs/angular/src/index.ts#L5

The most important folders for production code are `apps` and `libs`. You should find everything there. The lib `angular` depends on `core` and `transformer-support`. The lib `angular` should be used in the app `angular-karma-demo`. Every lib and app `tsconfig` is extended by the root one.

Maybe you can tell me what I am doing wrong. Thanks.

**Comment by nonara** [comment]
Couple of things:

1) You might want to check into yarn workspaces. 

    It looks like you might be doing some manual copying of files into node_modules and housing packages within packages. That can get frustrating and messy. I only had a second to look through a few files, so if I'm wrong, feel free to disregard.

    Otherwise, have a look at https://github.com/crosstype/crosstype to see an example of how yarn workspaces can help with 
multiple packages that rely on eachother in a mono-repo. 

2) Ideally, your transformer config file should be for your transformer only. If you need path mapping, replicate it there.

3) The 'tsConfig' property is relative to `cwd`, not the tsconfig file path. 

    This is probably the source of your issue.

If you still get an error after addressing 2 & 3, feel free to paste it in comments
