### ISSUE TITLE
Question / Possible Bug :: Plugins not working with TSC --build 

### ISSUE THREAD

**Issue by TylorS** [nonara/ts-patch#20]
Hello, first off thanks for this really awesome project, I'm really looking forward to using it.

At present I'm wondering if it's possible to use plugins when using `tsc --build /path/to/tsconfig`? 
I've added some log statements to the transformers I have installed, but I've had no luck with them running inside of build mode. Perhaps there's something I'm missing?

Thanks for your time.

**Comment by nonara** [comment]
Hi Tylor. Thanks for the kind words!

It should work in build mode, but I may have an idea of what is causing the issue. We originally forked from ttypescript's logic, which uses CWD for relative transformer resolution. If you're specifying a path outside of cwd for the project file and transformers paths are relative to the project file, they may simply not be resolving. This is something I've been meaning to address for awhile. 

If you wouldn't mind confirming if that's accurate in your case and letting me know, I'll update the logic and release as a new major. One way is to temporarily set absolute paths for the transformers and see if that helps.

**Comment by TylorS** [comment]
Thanks for the quick response. I don't believe that is the case. No rush or obligation, but I have a project (https://github.com/TylorS/typed-fp) that you should be able to take a look at. It's not released anywhere so the main branch has all the things I've been trying. `tsconfig.base.json` has the plugin configurations in question. After `npm install`, running `npm run build` is where I'd expect things to start happening, but I haven't had any luck. Any insight would be appreciated, thanks!

**Comment by TylorS** [comment]
Seems to have been something weird in my node_modules. I nuked them and tried again and all is well! Sorry for the false alarm. Thanks again for this library, it's incredibly useful to the TypeScript community.

**Comment by nonara** [comment]
No problem. Glad to hear it's worked out!

BTW, in case you run into any issues with `@zerollup/ts-transform-paths`, you might try [typescript-transform-paths](https://github.com/LeDDGroup/typescript-transform-paths). I used to use the zerollup package but I encountered a lot of issues, so I ended up switching to typescript-transform-paths. There were a few issues in that as well, so I re-wrote the library to rely entirely on the TS API for resolution. AFAIK, it should be the most stable option which is also tied directly to TS behaviour.

There's an open issue for TS4, however, which needs to be addressed, so if you're using TS4, you may want to wait for that to be fixed.

**Comment by TylorS** [comment]
In fact I am using TS4 for the variadic tuple support. I subscribed to the issue there and I'll look at replacing the plugin when it's been sorted.
