### ISSUE TITLE
[Feature Request] TransformationContext within a Transformer Program

### ISSUE THREAD

**Issue by LukasMachetanz** [nonara/ts-patch#30]
Hey!

I would like to access the `TransformationContext` within a `Transformer Program` (https://github.com/nonara/ts-patch#transforming-program).

I guess this is currently not possible, but in order to apply custom transformations within a `Transformer Program` it would be needed. Therefore I am looking for an enhancement of the interface.

**Comment by nonara** [comment]
Please see: [Transforming Program with additional AST transformations](https://github.com/nonara/ts-patch/discussions/29#discussioncomment-325979)
