### ISSUE TITLE
`ts-patch install` adds `ts-node` to dependencies

### ISSUE THREAD

**Issue by manuth** [nonara/ts-patch#38]
Installing the patch by invoking `npx ts-patch install` in my project's directory adds `ts-node` to my `package.json`s `dependencies`.
I don't think this is to be expected - also it's quite weird to have it added to `dependencies` instead of `devDependencies`.

Thanks for your awesome work - it's a great alternative to `ttypescript`!

**Comment by manuth** [comment]
My current workaround is adding `ts-node` to `devDependencies` before running `npx ts-patch install`.

**Comment by nonara** [comment]
@manuth Thanks for the report! You're right, that should not be added to deps! I'll get a fix out.
