### ISSUE TITLE
Breaks dependencies in mono repos when using yarn

### ISSUE THREAD

**Issue by patroza** [nonara/ts-patch#51]
If I install my dependencies with `yarn install --frozen-lockfile --production`
and `ts-node` is only part of my dev dependencies,
ts-patch will run `npm`, not `yarn`, and destroy my mono repo `node_modules`.

Desired fix:
- please use `yarn` when there's a `yarn.lock`
- alternatively; add an option to skip `npm` usage, and either throw a warning or an error when mismatch dependencies.

My workaround currently:
- moved `ts-node` to `dependencies`

**Comment by nonara** [comment]
Thanks for the report. That definitely isn't ideal. Overall, I'm of the opinion that it's better for `ts-patch` not to handing installing ts-node at all. I'll address that in the next patch

**Comment by nonara** [comment]
Fixed in v1.4.0 — `ts-node` is now no longer installed by the cli.

**Comment by patroza** [comment]
@nonara muchos gracias!

**Comment by manuth** [comment]
@nonara you might want to add a remark concerning this to the `README`.
Thanks for the great work, once more 😄

**Comment by nonara** [comment]
> you might want to add a remark concerning this to the `README`.

This is no longer an issue. `ts-patch` does not invoke any package managers. If `ts-node` is not found but is required, it will simply throw an error.

> Thanks for the great work, once more 😄

Sure thing!

**Comment by manuth** [comment]
Oh - yk, I thought of something like a remark that you have to install `ts-node` in the `Setup`-section of your readme:
https://github.com/nonara/ts-patch#setup

**Comment by nonara** [comment]
> I thought of something like a remark that you have to install `ts-node` in the `Setup`-section of your readme:

I considered it, but `ts-node` is not actually required to use `ts-patch`. The majority of people won't need it to be installed, as they are using transformer packages, which are already compiled to js. 

`ts-node` is only really necessary if you want to try to directly use a `.ts` transformer. In that case, it should be assumed that `ts-node` is necessary, but we also throw a pretty clear error message, so I think we're covered.

https://github.com/nonara/ts-patch/blob/541df51364cf277d003e3ab892ee8a3a2ec5a30f/src/patch/lib/plugin.ts#L163-L169

**Comment by manuth** [comment]
Awesome! Thanks for the explanation 😄
