### ISSUE TITLE
Cannot use with ts-node transpile-only

### ISSUE THREAD

**Issue by zyf0330** [nonara/ts-patch#53]

**Comment by nonara** [comment]
See issue: https://github.com/TypeStrong/ts-node/issues/1051

It is possible to use transformers with ts-node via the register method demonstrated in that issue.

**Comment by zyf0330** [comment]
I just don't want to use another transformer tool to support `ts-node --transpile-only`

**Comment by nonara** [comment]
At the moment, tsp does not natively patch the method used by ts-node. I will look at adding some sort of support for ts-node in v2.

That said, you don't need another tool to make it work. If you read the thread I posted, they give an example of supplying ts-node with your transformers, so you can make it work with or without patched typescript.

I should point out that most transformer packages for tsp or ttypescript require the type checker, so they will not work with transpile-only. The ones which take a raw signature should work, however.

You can try the one you like to find out. Just provide ts-node with your configuration like they do in the example I posted.

Hope that helps!

**Comment by zyf0330** [comment]
Thanks for your explanation!
I use a transformer **@zerollup/ts-transform-paths** which handles ts path mapping, I guess it doesn't need type checking.

**Comment by zyf0330** [comment]
Finally I use `ts-node -T -r tsconfig-paths/register` for develop, which doesn't need extra config.
