### ISSUE TITLE
Error on `ts-patch install`

### ISSUE THREAD

**Issue by nikita-starostin** [nonara/ts-patch#54]
I have run:
```
npm i -D ts-patch
ts-patch install
```
and get an error: `Could not recognize diagnostics signature in emitFilesAndReportErrors(). Please open an issue with your TS version #.`

The ts version is `3.1.8` the command is running inside the project created with `@angular/cli@7.1.4`

the version had been determined from running `tsc -v`, however the angular project has typescript3.1.6 in package.json as dependency.

**Comment by nikita-starostin** [comment]
I have also tried to 
```
npm i -D ts-patch@1.2.2.
ts-patch install
```

and had the same result

**Comment by nikita-starostin** [comment]
have done some debugging - have gone into the sources and find out where the error has been trown from, add some console log for more information:

![image](https://user-images.githubusercontent.com/57386894/127752897-79e003a1-f984-4c2d-be49-561524d8068c.png)

so the check for modern ts failed, then check for ts2.7 also failed

the logged rest code shows the next:
![image](https://user-images.githubusercontent.com/57386894/127752928-f0351f9a-e09a-47ce-b07a-88c42a04cdb5.png)
expectations that highlighted string should be found with 2.7 check

as next step have debugged the regex on regex101.com:
![image](https://user-images.githubusercontent.com/57386894/127752976-59375838-b746-4034-b0ba-43e32584154f.png)
from screen above the problem part is `(\)` which tries to find the call to `emit` function without parameters, e.g.
```
var _a = program.emit();
```

suggested fix: to remove `\)` from end of the regex (that will still catch calls without parameters and also catch calls with parameters), and then to handle possible case when the parameters have been passed

**Comment by nonara** [comment]
Ah, good catch. Thanks for the investigative work! Should be sorted in v1.4.2
