### ISSUE TITLE
Question: what does `ts-patch install` means?

### ISSUE THREAD

**Issue by loynoir** [nonara/ts-patch#57]
Hi, @nonara 

`ts-patch install` these name combos, to me it seems will modify typescript source code **in-place**.

Then is it?

Or it just create a layer or wrapper something?

If it so replace in-place

1. package manager like `pnpm` seems using hard link cache to save disk, will it pollute elsewhere?
2. If ts is system package, will it pollute global?
3. document with ☢☢☢ ?
4. document how it can be undo, and how safe the undo way is?

**Comment by nonara** [comment]
HI @loynoir 

I recommend calling `ts-patch /?` to see the options.

> package manager like pnpm seems using hard link cache to save disk, will it pollute elsewhere?

It does replace in-place, yes. If you're going to use `pnpm`, it should be understood that you're patching whatever is in node_modules. The upcoming v2 will operate differently.

With that said, the patch is minor and does not affect TS in any way, so there is no harm to having it patched more broadly, but this is something that should be taken into consideration when choosing a package manager for your project.

> If ts is system package, will it pollute global?

Again, I don't think 'pollute' is the right word, here, as adding the capability does not affect TS's speed or operability in any other way.

As far as patching the global installation of typescript (under other package managers), `ts-patch` can patch or unpatch it, by explicitly using a CLI argument.

> document how it can be undo, and how safe the undo way is?

There's one step installation and uninstallation. It is very stable and entirely reversible. This is all covered in the cli help.

Hope that helps!
