### ISSUE TITLE
Copy non-js files

### ISSUE THREAD

**Issue by juanrgm** [nonara/ts-patch#69]
It would be interesting to be able to copy non-js files (https://github.com/swimauger/tsc-hooks).

Could this library do it with some tweak?

**Comment by nonara** [comment]
You can do it without tweaking the library using a `Program Transformer`. You simply replace the passed `ts` instance's emit function and add your copy actions after calling the original emit method. I've built several build systems that do that sort of thing.

Hope that helps!
