### ISSUE TITLE
ts-patch isn't available on the command line.

### ISSUE THREAD

**Issue by Griffork** [nonara/ts-patch#72]
I installed ts-patch 2.0.1 using the following command:

```
npm install ts-patch --save-dev
```

It's installed successfully but running `ts-patch` or `npm ts-patch` on the command line in the same directory that the install command was used doesn't work with the following error:

```
ts-patch : The term 'ts-patch' is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

In the readme under "Setup" it says that I should be able to run the command `ts-patch install`.

**Comment by Griffork** [comment]
Oh! I found the answer, you have to do `npx ts-patch install`. Please update the readme for noobs like me!

**Comment by nonara** [comment]
Glad you got it working! It installs to .bin, like any similar package (ts-node, tsc, etc). If it isn't working, that is likely a config issue. But in that case, npx does work.
