### ISSUE TITLE
[Question] Error backing up tsc.js (read only filesystem)

### ISSUE THREAD

**Issue by IlyaSavichItr** [nonara/ts-patch#76]
Constantly getting error `[!] [BackupError]: Error backing up tsc.js - Couldn't create backup directory. EROFS: read-only filesystem, mkdir '/node_modules/typescript/lib-backup'`.

Trying with version 2.0.1

**Comment by nonara** [comment]
Hi @IlyaSavichItr ! 

Sorry to hear you're having issues. It sounds like you're trying to use ts-patch on a read only filesystem or one which can't be written to by the application. 

Because tsp directly modifies the files in node_modules, it needs the ability to write to the location.
