### ISSUE TITLE
A Diagnostic's source is not being respected when errors are emitted

### ISSUE THREAD

**Issue by sam-goodwin** [nonara/ts-patch#77]
For some reason, the `source` is not being included when emitting diagnostics. The below diagnostic will have the error code `TS123` instead of `TEST(123)`. 

The same code works properly in the Language Service though. Am i missing a configuration or is this is a limitation?

```ts
<typescript.Diagnostic>{
  source: "TEST",
  key: "TEST",
  category: ts.DiagnosticCategory.Error,
  code: 123,
  file: sf,
  start: node.pos,
  length: node.end - node.pos,
  messageText: `test error description`,
,

**Comment by nonara** [comment]
Hi Sam. Can you provide a little more detail? I'm not sure I'm following what's happening.

**Comment by sam-goodwin** [comment]
Sorry for not being clear. The problem was that I was trying to emit custom errors with a different error code than the standard TS error codes.

E.g. below is a standard error, `ts(2304)`.
```ts
Cannot find name 'undefi'.ts(2304)
```

I dug through the compiler code to find where the `ts` comes from with hopes of overriding it with a different value, e.g. `MyErrorCodeName(1234)`.

I think that is the `source` field in `ts.Diagnostic`, but it was getting lost. Sorry for opening this issue, after more digging, I think i discovered that the ts-compiler hard-codes the `ts` prefix, so it's not possible.

**Comment by nonara** [comment]
Ah, no worries! Glad you got it tracked out. Thanks for the update.
