### ISSUE TITLE
[Enhancement] Reduce dependencies.

### ISSUE THREAD

**Issue by MicahZoltu** [nonara/ts-patch#78]
ts-patch: 
![image](https://user-images.githubusercontent.com/886059/173177997-cbabc944-9141-4a62-bcf2-11a23413ac24.png)

ttypescript: 
![image](https://user-images.githubusercontent.com/886059/173178001-4a6d3315-80a2-463f-8fcf-7b29595b071e.png)

Unfortunately, ttypescript appears to be unmaintained and broken with `declarationMap: true`, but I'm very loath to bring in 35 dependencies to replace 1.

Is there any chance of getting the number of dependencies down to something much smaller (e.g., 0-5 total)?

**Comment by juanrgm** [comment]
Perhaps one of the reasons why it was abandoned was due to the extra cost of not having dependencies.

**Comment by nonara** [comment]
Hello. Thanks for the request.

I have two points I'd make on that.

First, the library was built to have an incredibly light footprint, which it does. While it may look like a bit, its memory size is small and overall, it's substantially less than most libraries would be.

Second, I would remind that this a development dependency. Relative to most like it, it is _very_ light.

That said, however, I would be happy to replace what we can. Some which would be great to replace would be:

- global-prefix
- shelljs (should be easily replaced at this point)
- resolve (_maybe_, we'd need to be sure that there are no side effects)

I would welcome PRs to reduce the footprint.

**Comment by nonara** [comment]
That's a good point. I believe a good strategy would be to replace what we can with local logic and we could use Webpack to bundle the rest for release.

If you or anyone want to get a PR going, I'd be happy to tag in to help where I can.

**Comment by nonara** [comment]
Going ahead and closing this for now. The new version dropped some deps, but they're not entirely eliminated.

A part of the roadmap for the next major version will be to use esbuild, however, which should alleviate some concerns.
