### ISSUE TITLE
TS 4.9

### ISSUE THREAD

**Issue by Alexandre-Fernandez** [nonara/ts-patch#82]
I'm using `ts-patch` with the `typescript-transform-paths` plugin and it looks like the new typescript update broke it, I switched back to TS `4.8.4` and it works again.

**Comment by nonara** [comment]
Thank you for the report. Can you give me a little more detail about what is happening?

Another user recently reported a regression in TS 4.9 that broke the visitEachChild function. He submitted a PR and I believe they are merging it.

**Comment by nonara** [comment]
This is the issue 

https://github.com/microsoft/TypeScript/issues/51542

Looks like this is pretty broad, so I'm assuming we need to wait on TS to release the patch.

**Comment by bradennapier** [comment]
More likely to be https://github.com/ovos/zerollup/pull/1 ?

**Comment by nonara** [comment]
> More likely to be https://github.com/ovos/zerollup/pull/1 ?

I don't think so, no. I accommodated 4.8 changes:

- https://github.com/LeDDGroup/typescript-transform-paths/commit/cbeb29cd3a62c205d7116a0ee5f0120d1696bd68

**Comment by DanielRosenwasser** [comment]
4.9.4 is now out FWIW

**Comment by nonara** [comment]
ts `4.9.4` support is added in ts-patch `v2.1.0`
