### ISSUE TITLE
Will the plugin affect the generation of sourceMap?

### ISSUE THREAD

**Issue by zhfnjust** [nonara/ts-patch#84]
Our plugin inserts some code in the generated js file when TS is compiled, which seems to cause sourcemap to become confused, and the breakpoint set when debugging Ts does not work

**Comment by zhfnjust** [comment]
this is my tsconfig:

```json
{
  "compilerOptions": {
    /* Language and Environment */
    "target": "es2021", /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
    "lib": [
      "es2021"
    ], /* Specify a set of bundled library declaration files that describe the target runtime environment. */
    "experimentalDecorators": true, /* Enable experimental support for TC39 stage 2 draft decorators. */
    /* Modules */
    "module": "commonjs", /* Specify what module code is generated. */
    "rootDir": "./", /* Specify the root folder within your source files. */
    "moduleResolution": "node", /* Specify how TypeScript looks up a file from a given module specifier. */
    "outDir": "./dist", /* Specify an output folder for all emitted files. */
    "esModuleInterop": true, /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables 'allowSyntheticDefaultImports' for type compatibility. */
    /* Type Checking */
    /* "strict": true,                                       Enable all strict type-checking options. */
    "skipLibCheck": true /* Skip type checking all .d.ts files. */,
    "sourceMap": true,
    "plugins": [
      {
        "transform": "scrypt-ts/dist/transformer",
        "outDir": "./scrypts",
        "transformProgram": true,
        "debug": true
      }
    ]
  },
  "include": [
    "contracts/**/*.ts",
    "tests/**/*.ts"
  ]
}
```

**Comment by WalterWoshid** [comment]
It probably will, yes. If you change your javascript file with a plugin **after** it's source map's been generated, you have to renew the source map. You could achieve that with [magic-string](https://github.com/Rich-Harris/magic-string)

**Comment by zhfnjust** [comment]
When starting the debugger, it always automatically stops at the last line of the generated js file no matter where I set the breakpoint.

<img width="1393" alt="image" src="https://user-images.githubusercontent.com/995909/204141257-0f590ec6-845c-43da-b80f-34b365083239.png">

Here is the minimal codebase to reproduce the problem： 

https://github.com/zhfnjust/plugin-ts

**Comment by WalterWoshid** [comment]
@zhfnjust Have you placed the breakpoint in the JS or the TS file? It is working for me without any problems on WebStorm and VSCode and breaks in whatever file I place the breakpoint

**Comment by WalterWoshid** [comment]
Can you show the generated `test/out/test/main.test.js` and `test/out/test/main.test.js.map` file?

**Comment by zhfnjust** [comment]
yes, i have set breakpoint at this line: https://github.com/zhfnjust/plugin-ts/blob/77b933b152fc1518a0b6ac051da989cd36bff9f9/test/main.test.ts#L25

main.test.js:

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Demo = void 0;
function assert(cond) {
    console.log("assert", cond);
}
class Demo {
    constructor(x, y) {
        this.x = x;
        this.y = y;
    }
    sum(a, b) {
        return a + b;
    }
    add(z) {
        assert(z == this.sum(this.x, this.y));
    }
    sub(z) {
        assert(z == this.x - this.y);
    }
}
exports.Demo = Demo;
let demo = new Demo(1n, 2n);
demo.add(3n);
//# sourceMappingURL=main.test.js.map
```

main.test.js.map:

```json
{"version":3,"file":"main.test.js","sourceRoot":"","sources":["../../main.test.ts"],"names":[],"mappings":";;;AAAA,SAAS,MAAM,CAAC,IAAa;IACzB,OAAO,CAAC,GAAG,CAAC,QAAQ,EAAE,IAAI,CAAC,CAAC;AAChC,CAAC;AACD,MAAa,IAAI;IAGb,YAAY,CAAS,EAAE,CAAS;QAC5B,IAAI,CAAC,CAAC,GAAG,CAAC,CAAC;QACX,IAAI,CAAC,CAAC,GAAG,CAAC,CAAC;IACf,CAAC;IACD,GAAG,CAAC,CAAS,EAAE,CAAS;QACpB,OAAO,CAAC,GAAG,CAAC,CAAC;IACjB,CAAC;IACM,GAAG,CAAC,CAAS;QAChB,MAAM,CAAC,CAAC,IAAI,IAAI,CAAC,GAAG,CAAC,IAAI,CAAC,CAAC,EAAE,IAAI,CAAC,CAAC,CAAC,CAAC,CAAC;IAC1C,CAAC;IACM,GAAG,CAAC,CAAS;QAChB,MAAM,CAAC,CAAC,IAAI,IAAI,CAAC,CAAC,GAAG,IAAI,CAAC,CAAC,CAAC,CAAC;IACjC,CAAC;CACJ;AAhBD,oBAgBC;AACD,IAAI,IAAI,GAAG,IAAI,IAAI,CAAC,EAAE,EAAE,EAAE,CAAC,CAAC;AAC5B,IAAI,CAAC,GAAG,CAAC,EAAE,CAAC,CAAC"}
```

**Comment by WalterWoshid** [comment]
Interesting, I see some differences in your source map and also in your generated file, my generated file has `'include'` instead of `"include"`. Not sure why though

**Comment by WalterWoshid** [comment]
Building the project with WSL2 (Linux) generates the same issue, it doesn't break inside the TypeScript file

**Comment by WalterWoshid** [comment]
I found the solution! Don't use the `printFile(sourceFile)` method, just use `sourceFile.text` :)

**Comment by nonara** [comment]
This is unfortunately a known limitation with program transformers. The generated source map points back to the modified source file, so it won't work with the original.

It would be good if we could find a way to re-walk the types so we didn't need to do it this way.

**Comment by zhfnjust** [comment]
> This is unfortunately a known limitation with program transformers. The generated source map points back to the modified source file, so it won't work with the original.
> 
> It would be good if we could find a way to re-walk the types so we didn't need to do it this way.

Are you saying that there is currently no solution to this problem?

**Comment by nonara** [comment]
None that I know of. It isn't unsolvable, by any means, but it would take some work to do it.

The best route would likely be find where the source mapping detail is saved on the `SourceFile` node and its children and make sure it's copied over for known nodes.

Simply put, you'd need to do some debugging and experimentation, digging into how source maps are generated. If you decide to so so and find a way, I'll be glad to update the example code.

**Comment by WalterWoshid** [comment]
@nonara The problem with modifying the source before it gets transformed to JavaScript, how should the debugger know where the changed part of the code is inside the original code? For example you remove a whole function from the source and now you place a breakpoint in the source file, where should it stop? Nowhere would work, but if you **add** code instead of remove, how would it know that?

**Comment by nonara** [comment]
@WalterWoshid source map is meant to point back to existing code.

When a node is transformed, the position property is set to -1, indicating that it does not have a position in the original file.

I am assuming that this property is what is used, and it is most likely on a statement level that it's considered.

That in mind, I'm guessing any statement level node which gets modified (or added) does not have associated source mapping.

So if it is as simple as using pos, you might be able to fix this by adding a step after your Program exchange.

That step would:

Walk all nodes on the new program's source file and copy over the `pos` value from the associated _transformed_ original source files.

This should work as all nodes should match 1 to 1. Assuming source map uses pos, that should work

Assuming source maps use that

**Comment by WalterWoshid** [comment]
@nonara I understand and that probably is good enough if you only change nodes. But as soon as you add or remove multiple nodes to/from the ast tree you have sections that don't apply to the previous source file. You'd have JavaScript code that doesnt match any breakpoint in the original source file and you'd need to output the new transformed source file (source__transformed.ts) where you would put your breakpoints inside.

**Comment by WalterWoshid** [comment]
@nonara I see, thanks for the clarification. But what happens if you jump one step, would it point back to the JavaScript source file? Or would it just jump to the next available stepping point?

I could try to do something with the magic-string package on npm to resolve the existing positions, if interested.

**Comment by roman-shpp** [comment]
@nonara is there any hope to fix the issue? I've recently discovered Typia project (which uses `ts-patch`) and really felt in love with it, however broken stack traces are sooo demotivating :(

**Comment by nonara** [comment]
@roman-shpp I understand. It's unfortunately not a trivial problem. 

That said, I've given some thought to it, and I have a new feature planned which will provide a better solution for people who simply need to get type data for transformed files, which I believe covers most of the use cases where this is a factor. I'm not sure about the library you're referring to, though.

I will add it to the spec for the ts rewrite, and we will hopefully begin that soon.
