### ISSUE TITLE
Example how to run/test an transformer with tsc/ts-node

### ISSUE THREAD

**Issue by dkryaklin** [nonara/ts-patch#87]
Hello,

I'm a bit struggling to run my transformer together with `tsc` or `ts-node` after `ts-patch install`.

When I run it with `tsc` it doesn't really care whether there is a plugin in tsconfig.json or not.
For `ts-node` seems working at first, but there are random errors. 

So my proposal is to have some boilerplate example that 100% works with both `tsc` or `ts-node`.
Happy to provide PR with some guidance.

**Comment by nonara** [comment]
Hi @dkryaklin! Thanks for the message. 

There is no difference in transformer performance between ts-node or tsc. All transformers are compatible with either.

I would recommend making sure the libraries are patched (`ts-patch check`) and use `which tsc` to make sure that you're hitting the correct one.

As for writing transformers, there are some linked articles in the [Recommended Reading](https://github.com/nonara/ts-patch#recommended-reading) section.

I agree, however, that it would be good to have an example transformer. We will consider adding that to the upcoming rewritten version. In the mean time, you can see examples here: https://github.com/nonara/ts-patch/tree/master/test/assets/transformers

Best of luck!
