### ISSUE TITLE
Tests break on Windows

### ISSUE THREAD

**Issue by WalterWoshid** [nonara/ts-patch#88]
I'm assuming this is a problem with windows.

When running the tests, they fail in the file `src/installer/lib/file-utils.ts` in the `getTSPackage()` function when the project path directory is passed. The `fs.existsSync` function returns `false` for any file or folder. When logging the result of `ts.readdirSync` on the project folder it returns only one folder, the `dist` folder. Running the command from the CLI, even while the test is running, works for both functions.

**Comment by WalterWoshid** [comment]
Weirdly enough, this does not happen on my Windows laptop. Maybe there are some problems with the permissions or because I linked this library with `yarn link`

**Comment by nonara** [comment]
Try resetting yarn lock on both machines and re-installing. I believe tests use mock-fs, which hooks filesystem bindings. That would be my first guess as to where something is going wrong

**Comment by nonara** [comment]
Hi @WalterWoshid! I pulled this and ran it on Windows without issue with a fresh lockfile.

I'm guessing the issue was a bad release somewhere. If you do a full reset and have an issue still, let me know, and we'll reopen this.
