### ISSUE TITLE
How to integrate with webpack

### ISSUE THREAD

**Issue by zhfnjust** [nonara/ts-patch#91]
we use ts-patch as transformProgram,  we create source file with updated text:

```ts
  const newFile = tsInstance.createSourceFile(fileName, updatedText, languageVersion, true);
```

and it works fine if we build with `npx tsc`. 

But when I bundle the code with webpack and run it in the browser, it doesn't work.

**Comment by nonara** [comment]
Hello. Thanks for the comment.

In order to help, I would need to see a reproduction and have some more detail. If you'd like to update this with a repro + detail, I will reopen.
